apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    jsonData:
      derivedFields:
        - name: Trace
          matchRegex: trace_id="([a-fA-F0-9]+)"
          url: "http://localhost:3200/api/traces/${__value.regex[1]}"

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: false
    jsonData:
      httpProtocol: http
      tracesToLogs:
        datasourceUid: loki
        customQuery: true
        query: '{app="otel"} | trace_id="${__span.traceId}"'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
